"""tabele

Revision ID: 90fb50a43c81
Revises: 
Create Date: 2023-02-27 13:08:30.770108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fb50a43c81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sample')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('meteo_data')
    op.drop_table('fardata_pm_raw_data')
    op.drop_table('fardata_noise_level')
    op.drop_table('fardata_atmo_data')
    op.drop_table('STACJE_METEO')
    op.drop_table('Logger')
    # ### end Alembic commands ###
